version: '3'
services:
  app:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${PWD}/html:/var/www/html
    ports:
      - 8080:80
    network_mode: php-mysql #作成したカスタムネットワークの名前
    restart: always

  db1:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      # MySQLの設定ファイル
      - ./mysql/mysql_conf:/etc/mysql/conf.d
      # データベースのデータ
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    network_mode: php-mysql #作成したカスタムネットワークの名前
    restart: always

networks:
  php-mysql:
